### ISSUE TITLE
Support arrays

### ISSUE THREAD

**Issue by shadoWalker89** [micheleangioni/laravel-js-lang-converter#10]
Hi,

So i have a lang file called "common.php" that contains something like this

``` php
return [
    'month_names' => [/*An array of the month names*/]
];
```

When i do 

``` javascript
Lang.get('common.month_names')
```

I get `common.month_names` instead of the array or object

**Comment by micheleangioni** [comment]
Hi @shadoWalker89 ,
only strings and objects are supported, e.g.

``` js
return [
    'month_names' => { /*months object*/ }
];
```

See #9 for reference.

Best Regards.
